name = "S2OCT"
uuid = "66f729a7-8539-475b-8194-85a56a9a6c42"
authors = ["mariaepinheiro <pinheiro@uni-trier.de\ngit config --global user.email pinheiro@uni-trier.de\ngit config --global user.email pinheiro@uni-trier.de>"]
version = "0.1.0"

[deps]
Gurobi = "2e9cd046-0924-5485-92f1-d5272153d98b"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
Gurobi="10.0"
